import "./globals.css";
import { Roboto } from "next/font/google";
import Context from "./context/Context";
import Providers from "./providers";


const RobotoSans = Roboto({
  variable: "--font-Roboto-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${RobotoSans.variable}  antialiased bg-background w-full h-auto`}
      >
        <Providers>
          <Context>
            {children}
          </Context>
        </Providers>
      </body>
    </html>
  );
}
