import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Roboto } from "next/font/google";
import Context from "./context/Context";

const RobotoSans = Roboto({
  variable: "--font-Roboto-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${RobotoSans.variable}  antialiased bg-background w-full h-auto pb-20`}
      >
        <Context>
          <NavBar />
          {children}
        </Context>
      </body>
    </html>
  );
}
