// import "../globals.css";
import "@/app/globals.css"
import NavBar from "@/components/NavBar";
import { Roboto } from "next/font/google";


const RobotoSans = Roboto({
    variable: "--font-Roboto-sans",
    subsets: ["latin"],
});



export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${RobotoSans.variable}  antialiased bg-background w-full h-auto overflow-x-hidden`}
            >
                <NavBar />
                {children}
            </body>
        </html>
    );
}
