// import "../globals.css";
import "@/app/globals.css"
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { ContextProvider } from "@/app/context/Context"
import { Roboto } from "next/font/google";


const RobotoSans = Roboto({
    variable: "--font-Roboto-sans",
    subsets: ["latin"],
});



export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function UserLayout({ children }) {
    return (
        <div dir="rtl" lang="ar" className={`${RobotoSans.variable} font-sans antialiased bg-background w-full max-w-full min-h-screen overflow-x-hidden`}>
            {/* NavBar is now in HomeClient, so remove from here or keep if needed on all pages */}
            <NavBar />
            {children}
            <Footer />
        </div>
    );
}
