// import "../globals.css";
import "@/app/globals.css"
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { ContextProvider } from "@/app/context/Context"
import { Roboto, Rubik } from "next/font/google";
import { getPromotions } from '@/lib/server-fetch';


const RobotoSans = Roboto({
    variable: "--font-Roboto-sans",
    subsets: ["latin"],
});

const RubikSans = Rubik({
  variable: "--font-Rubik-sans",
  subsets: ["latin"],
})


export const metadata = {
    title: "La Maison D'or",
    description: "Generated by create next app",
};

export default async function UserLayout({ children }) {
    const promotions = await getPromotions();

    return (
        <div dir="rtl" lang="ar" className={`${RubikSans.variable} font-sans antialiased bg-background w-full max-w-full min-h-screen `}>
            <ContextProvider initialPromotions={promotions}>
                <NavBar />
                {children}
                <Footer />
            </ContextProvider>
        </div>
    );
}