import { DashBoardSideBar } from "@/components/DashBoardSideBar";
import { Roboto } from "next/font/google";


const RobotoSans = Roboto({
    variable: "--font-Roboto-sans",
    subsets: ["latin"],
});



export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${RobotoSans.variable}  antialiased bg-background w-full h-auto`}
            >
                <div className="w-full h-auto flex">
                    <DashBoardSideBar />
                    {children}
                </div>
            </body>
        </html>
    );
}
