// lib/wilayaData.js
export const wilayaData = {
  "02": {
    name: "Chlef",
    domicilePrice: 800,
    stopDeskPrice: 500,
    municipalities: [
      "Chlef",
      "Ténès",
      "Beni Haoua",
      "El Karimia",
      "Taougrite",
      "Beni Rached",
      "Sobha",
      "Harenfa",
      "Oued Fodda",
      "Ouled Fares",
      "Boukadir",
      "Benairia",
      "El Marsa",
      "Oued Sly",
      "Abou El Hassen",
      "El Hadjadj",
      "Chettia",
      "Sendjas",
      "Zeboudja",
      "Oum Drou",
      "Bouzeghaia",
      "Dahra",
      "Beni Bouateb",
      "Talassa",
      "Sidi Akkacha",
      "Sidi Abderrahmane",
      "Tadjena",
      "El Abadia",
      "Breira",
      "Moussadek",
      "Ouled Ben Abdelkader",
      "Bouguirat",
      "Beni Moussa",
      "Ain Merane",
      "Sidi Yakoub",
    ],
  },
  "03": {
    name: "Laghouat",
    domicilePrice: 900,
    stopDeskPrice: 550,
    municipalities: [
      "Laghouat",
      "Ksar El Hirane",
      "Benacer Benchohra",
      "Sidi Makhlouf",
      "Tadjmout",
      "El Ghicha",
      "Aïn Madhi",
      "El Assafia",
      "Brida",
      "El Houaita",
      "Sidi Bouzid",
      "Tadjrouna",
      "El Haouaita",
      "Gueltat Sidi Saad",
      "Aïn Sidi Ali",
      "Oued Morra",
      "Oued M'zi",
      "Sebgag",
      "Hassi Delaa",
      "Hassi R'Mel",
      "Boualem",
      "El Kheneg",
      "Sidi Slimane",
      "Afou",
    ],
  },
  "04": {
    name: "Oum El Bouaghi",
    domicilePrice: 700,
    stopDeskPrice: 450,
    municipalities: [
      "Oum El Bouaghi",
      "Ain Babouche",
      "Behir Chergui",
      "El Amiria",
      "El Belala",
      "El Djazia",
      "El Fedjoudj",
      "El Harmilia",
      "El Mizaraa",
      "Fkirina",
      "Ksar Sbahi",
      "Meskiana",
      "Oued Nini",
      "Ouled Gacem",
      "Ouled Hamla",
      "Ouled Zekri",
      "Raihana",
      "Sigus",
      "Souk Naamane",
      "Zorg",
      "Ain Beida",
      "Ain Diss",
      "Ain Fakroun",
      "Ain Kercha",
      "Ain M'lila",
      "Berriche",
      "Dhalaa",
      "Hanchir Toumghani",
      "Ksar Ouled Derradj",
    ],
  },
  "05": {
    name: "Batna",
    domicilePrice: 700,
    stopDeskPrice: 450,
    municipalities: [
      "Aïn Djasser",
      "Aïn Touta",
      "Aïn Yagout",
      "Arris",
      "Azil Abderrahmane",
      "Barika",
      "Batna",
      "Belezma",
      "Beni Fouda",
      "Bitam",
      "Boulhilat",
      "Boumaguer",
      "Boumia",
      "Bouzina",
      "Chemora",
      "Chouchi",
      "Djezzar",
      "El Madher",
      "Fesdis",
      "Foum Toub",
      "Ghassira",
      "Gosbat",
      "Guigba",
      "Hidoussa",
      "Ichmoul",
      "Inoughissen",
      "Kimmel",
      "Larbaa",
      "Lazrou",
      "Lemcene",
      "Maâfa",
      "Menaâ",
      "Merouana",
      "N’Gaous",
      "Oued Chaaba",
      "Oued El Ma",
      "Oued Taga",
      "Ouled Ameur",
      "Ouled Aouf",
      "Ouled Fadel",
      "Ouled Maïz",
      "Ouled Sellam",
      "Ouled Si Slimane",
      "Ouyoun El Assafir",
      "Rahbat",
      "Ras El Aioun",
      "Sefiane",
      "Seggana",
      "Seriana",
      "T’Kout",
      "Tazoult",
      "Teniet El Abed",
      "Tighanimine",
      "Tigherghar",
      "Tilatou",
      "Timgad",
      "Taxlent",
      "Tifelfel",
      "Zab",
      "Zakhar",
      "Zanaet El Beida",
    ],
  },
  "06": {
    name: "Béjaïa",
    domicilePrice: 600,
    stopDeskPrice: 400,
    municipalities: [
      "Adekar",
      "Aït R'zine",
      "Aït Smaïl",
      "Akbou",
      "Akfadou",
      "Amalou",
      "Amizour",
      "Aokas",
      "Barbacha",
      "Béjaïa",
      "Beni Djellil",
      "Beni Ksila",
      "Beni Maouche",
      "Beni Mellikeche",
      "Boudjellil",
      "Bouhamza",
      "Boukhelifa",
      "Chellata",
      "Chemini",
      "Darguina",
      "Draâ El Kaïd",
      "El Kseur",
      "Fenaïa Ilmaten",
      "Ferraoun",
      "Guenzet",
      "Ifelain Ilmaten",
      "Ighil Ali",
      "Kendira",
      "Kherrata",
      "Leflaye",
      "M'Cisna",
      "Melbou",
      "Oued Ghir",
      "Ouzellaguen",
      "Semaoun",
      "Sidi Aïch",
      "Sidi Ayad",
      "Slimane",
      "Souk El Tenine",
      "Souk Oufella",
      "Tala Hamza",
      "Tamokra",
      "Tamridjet",
      "Taourirt Ighil",
      "Tazmalt",
      "Tibane",
      "Tichy",
      "Tifra",
      "Timezrit",
      "Tinabdher",
      "Tizi N'Berber",
      "Toudja",
    ],
  },
  "07": {
    name: "Biskra",
    domicilePrice: 900,
    stopDeskPrice: 550,
    municipalities: [
      "Aïn Naga",
      "Aïn Zaatout",
      "Besbes",
      "Biskra",
      "Bordj Ben Azzouz",
      "Branis",
      "Chetma",
      "Djemorah",
      "Doucen",
      "Eulma",
      "Feidh El Botma",
      "Foughala",
      "Kheneg",
      "Lichana",
      "Lioua",
      "M'Chouneche",
      "Meziraa",
      "M'Lili",
      "Ouled Djellal",
      "Ouled Harkat",
      "Ouled Rahmoune",
      "Ouled Sassi",
      "Oumache",
      "Ourlal",
      "Sidi Khaled",
      "Sidi Okba",
      "Tolga",
      "Zeribet El Oued",
      "El Hadjab",
      "El Haouch",
      "El Outaya",
      "Ghrous",
      "Sidi Slimane",
    ],
  },
  "09": {
    name: "Blida",
    domicilePrice: 750,
    stopDeskPrice: 450,
    municipalities: [
      "Blida",
      "Ain Romana",
      "Beni Mered",
      "Beni Tamou",
      "Bouarfa",
      "Boufarik",
      "Bougara",
      "Bouinan",
      "Chebli",
      "Chiffa",
      "Djebabra",
      "El Affroun",
      "Guerrouaou",
      "Hammam Elouane",
      "Larbaa",
      "Meftah",
      "Mouzaia",
      "Oued Alleug",
      "Oued Djer",
      "Ouled Yaich",
      "Souhane",
      "Soumaa",
      "Ben Khlil",
      "Beni Saleh",
      "Tablat",
    ],
  },
  "10": {
    name: "Bouira",
    domicilePrice: 600,
    stopDeskPrice: 400,
    municipalities: [
      "Aïn Bessem",
      "Aïn El Hadjar",
      "Aïn Laloui",
      "Aïn Turk",
      "Aït Laaziz",
      "Ath Mansour",
      "Bouira",
      "Bordj Okhriss",
      "Chorfa",
      "Dechmia",
      "Dirrah",
      "Djebahia",
      "El Adjiba",
      "El Asnam",
      "El Hachimia",
      "El Khabouzia",
      "El Mokrani",
      "Guerrouma",
      "Haizer",
      "Kadiria",
      "Lakhdaria",
      "M'Chedellah",
      "Maala",
      "Maamora",
      "Oued El Berdi",
      "Ouled Rached",
      "Raouraoua",
      "Ridane",
      "Saharidj",
      "Souk El Ghozlane",
      "Taguedit",
      "Taghzout",
      "Zbarbar",
      "Aïn El Ibel",
      "Aïn Soltane",
      "Aït Bouadou",
      "Aït Oumalou",
      "Bir Ghbalou",
      "Bouderbala",
      "Boukram",
      "Dirah",
      "El Hassania",
      "Hanif",
      "Khedara",
      "Mezdour",
      "Oued Djemaa",
      "Ouled Brahim",
      "Ouled Mansour",
      "Oum El Adhaim",
    ],
  },
  "12": {
    name: "Tébessa",
    domicilePrice: 750,
    stopDeskPrice: 450,
    municipalities: [
      "Tébessa",
      "Ain Zerga",
      "Bekkaria",
      "Bir El Ater",
      "Bir Mokkadem",
      "Boulhaf Dir",
      "El Aouinet",
      "El Kouif",
      "El Malabiod",
      "El Ogla",
      "El Ogla El Malha",
      "Ferkane",
      "Guorriguer",
      "Hammamet",
      "Morsott",
      "Negrine",
      "Ouenza",
      "Oum Ali",
      "Sakiet Sidi Youssef",
      "Stah Guentis",
      "Tlidjene",
      "Bir Dheheb",
      "El Meridj",
      "El Mezeraa",
      "Oued El Khrouf",
      "Ouled Brahim",
      "Ouled Chouikh",
      "Sidi Rached",
    ],
  },
  "13": {
    name: "Tlemcen",
    domicilePrice: 800,
    stopDeskPrice: 500,
    municipalities: [
      "Tlemcen",
      "Ain Fetah",
      "Ain Ghoraba",
      "Ain Kebira",
      "Ain Nehala",
      "Ain Tellout",
      "Ain Youcef",
      "Amieur",
      "Azails",
      "Bab El Assa",
      "Beni Bahdel",
      "Beni Boussaid",
      "Beni Mester",
      "Beni Ouarsous",
      "Beni Snous",
      "Bensekrane",
      "Bouhlou",
      "Chetouane",
      "El Aricha",
      "El Bouihi",
      "El Fehoul",
      "El Gor",
      "Hennaya",
      "Honaine",
      "Mansourah",
      "Marsa Ben M'Hidi",
      "Nedroma",
      "Oued Lakhdar",
      "Ouled Mimoun",
      "Ouled Riyah",
      "Remchi",
      "Sabra",
      "Sebdou",
      "Sidi Abdelli",
      "Sidi Djillali",
      "Sidi Medjahed",
      "Souahlia",
      "Souk Thlata",
      "Souani",
      "Tienet",
      "Zenata",
      "Beni Khellad",
      "Beni Ouillane",
      "Beni Smiel",
      "Bouhadjar",
      "El Kala",
      "El Tarf",
      "Hammam Beni Salah",
      "Ouled Kihal",
      "Ouled Mohamed",
      "Sidi Ben Adda",
      "Sidi Boumediene",
      "Zemmoura",
    ],
  },
  "14": {
    name: "Tiaret",
    domicilePrice: 750,
    stopDeskPrice: 450,
    municipalities: [
      "Tiaret",
      "Ain Bouchekif",
      "Ain Deheb",
      "Ain El Hadid",
      "Ain Kermes",
      "Ain Zarit",
      "Bouchekif",
      "Chehaima",
      "Dahmouni",
      "Djebilet Rosfa",
      "Faidja",
      "Frenda",
      "Hamadia",
      "Ksar Chellala",
      "Madna",
      "Mahdia",
      "Mechraa Safa",
      "Medrissa",
      "Mellakou",
      "Nadorah",
      "Naima",
      "Oued Lilli",
      "Rahouia",
      "Rechaiga",
      "Sebdou",
      "Seghouane",
      "Si Abdelghani",
      "Sidi Abderrahmane",
      "Sidi Ali Mellal",
      "Sidi Bakhti",
      "Sidi Hosni",
      "Sougueur",
      "Tagdempt",
      "Tadjmout",
      "Takhemaret",
      "Tousnina",
      "Zmalet El Emir",
      "Zmalet El Emir Abdelkader",
    ],
  },
  "15": {
    name: "Tizi Ouzou",
    domicilePrice: 700,
    stopDeskPrice: 450,
    municipalities: [
      "Tizi Ouzou",
      "Aïn El Hammam",
      "Azazga",
      "Beni Douala",
      "Beni Yenni",
      "Boghni",
      "Bouzeguene",
      "Draâ Ben Khedda",
      "Freha",
      "Iferhounène",
      "Larbaâ Nath Irathen",
      "Maâtka",
      "Makouda",
      "Mekla",
      "Ouacifs",
      "Ouadhias",
      "Ouaguenoun",
      "Sidi Naâmane",
      "Tadmaït",
      "Tigzirt",
      "Timizart",
      "Tirmitine",
      "Aït Aïssa Mimoun",
      "Aït Bouaddou",
      "Aït Boumahdi",
      "Aït Chafâa",
      "Aït Khellili",
      "Aït Mahmoud",
      "Aït Oumalou",
      "Aït Toudert",
      "Aït Yahia",
      "Aït Yahia Moussa",
      "Assi Youcef",
      "Beni Aïssi",
      "Beni Ziki",
      "Boudjima",
      "Djebel Aissa Mimoun",
      "Djebel Bouna",
      "Djebel Draâ",
      "Djebel Z'hor",
      "Draâ El Mizan",
      "Iflissen",
      "Imsouhal",
      "Irdjen",
      "Khemis El Khechna",
      "Larbaâ",
      "Mechtras",
      "Mizrana",
      "Naciria",
      "Sidi Daoud",
      "Souk El Thenine",
      "Taourirt Moussa",
      "Tizi N'Tleta",
      "Tizi Rached",
      "Yakouren",
      "Zekri",
    ],
  },
  "16": {
    name: "Alger",
    domicilePrice: 600,
    stopDeskPrice: 400,
    municipalities: [
      "Alger Centre",
      "Sidi M'Hamed",
      "El Madania",
      "El Mouradia",
      "El Biar",
      "Bouzareah",
      "Bab El Oued",
      "Bologhine",
      "Casbah",
      "Oued Koriche",
      "Hussein Dey",
      "Kouba",
      "Bachedjerah",
      "El Harrach",
      "Baraki",
      "Oued Smar",
      "Dar El Beïda",
      "Bab Ezzouar",
      "Bordj El Kiffan",
      "Bordj El Bahri",
      "El Marsa",
      "Aïn Taya",
      "Rouïba",
      "Reghaïa",
      "Mohammadia",
      "Birkhadem",
      "Saoula",
      "Draria",
      "Ouled Chebel",
      "Sidi Moussa",
      "Tessala El Merdja",
      "Rahmania",
      "Zeralda",
      "Mahelma",
      "Staoueli",
      "Aïn Benian",
      "Dely Ibrahim",
      "Cheraga",
      "Ouled Fayet",
      "El Achour",
      "Ben Aknoun",
      "Hydra",
      "Les Bananiers",
      "Climat de France",
      "El Hamiz",
      "La Montagne",
      "Beaulieu",
      "La Concorde",
      "Les Sources",
      "Les Annassers",
    ],
  },
  "17": {
    name: "Djelfa",
    domicilePrice: 850,
    stopDeskPrice: 500,
    municipalities: [
      "Djelfa",
      "Ain El Ibel",
      "Ain Oussera",
      "Birine",
      "Bouira Lahdab",
      "Charef",
      "Dar Chioukh",
      "El Idrissia",
      "Faidh El Botma",
      "Had Sahary",
      "Hassi Bahbah",
      "Messaad",
      "Sed Rahal",
      "Sidi Baïzid",
      "Sidi Ladjel",
      "Tadmit",
      "Zaccar",
    ],
  },
  "18": {
    name: "Jijel",
    domicilePrice: 700,
    stopDeskPrice: 500,
    municipalities: [
      "Jijel",
      "El Aouana",
      "El Milia",
      "Settara",
      "Taher",
      "Ziama Mansouriah",
      "Bouraoui Belhadef",
      "Chekfa",
      "Djimla",
      "Emir Abdelkader",
      "Eraguene",
      "Ghabdeloued",
      "Kaous",
      "Kheïri Oued Adjoul",
      "Oudjana",
      "Ouled Rabah",
      "Selma Benziada",
      "Sidi Maarouf",
      "Texenna",
    ],
  },
  "19": {
    name: "Sétif",
    domicilePrice: 500,
    stopDeskPrice: 400,
    municipalities: [
      "Sétif",
      "Aïn Abessa",
      "Aïn Azel",
      "Aïn El Kebira",
      "Aïn Oulmane",
      "Amoucha",
      "Babor",
      "Bazer Sakhra",
      "Beidha Bordj",
      "Belaa",
      "Beni Aziz",
      "Beni Chebana",
      "Beni Fouda",
      "Beni Hocine",
      "Beni Ourtilane",
      "Bir El Arch",
      "Bouandas",
      "Bougaa",
      "Bousselam",
      "Boutaleb",
      "Dehamcha",
      "Djemila",
      "El Eulma",
      "El Ouldja",
      "Guellal",
      "Guelta Zerka",
      "Guidjel",
      "Hammam Guergour",
      "Hammam Souhna",
      "Maoklane",
      "Mezloug",
      "Ouled Addouane",
      "Ouled Sabor",
      "Ouled Si Ahmed",
      "Ouled Tebben",
      "Rasfa",
      "Salah Bey",
      "Serdj El Ghoul",
      "Tachouda",
      "Talaifacene",
      "Taya",
      "Tella",
    ],
  },
  "20": {
    name: "Saïda",
    domicilePrice: 900,
    stopDeskPrice: 550,
    municipalities: [
      "Saïda",
      "Ain El Hadjar",
      "Doui Thabet",
      "El Hassasna",
      "Hounet",
      "Maamora",
      "Ouled Brahim",
      "Ouled Khaled",
      "Sidi Ahmed",
      "Sidi Amar",
      "Sidi Boubekeur",
      "Tircine",
      "Youb",
    ],
  },
  "22": {
    name: "Sidi Bel Abbès",
    domicilePrice: 800,
    stopDeskPrice: 500,
    municipalities: [
      "Sidi Bel Abbès",
      "Ain Adden",
      "Ain El Berd",
      "Ben Badis",
      "Bir El Hammam",
      "Boukhanafis",
      "Dhaya",
      "El Hacaiba",
      "Hassi Dahou",
      "Hassi Zahana",
      "Makedra",
      "Marhoum",
      "Moulay Slissen",
      "Ras El Ma",
      "Redjem Demouche",
      "Sehala Thaoura",
      "Sidi Ali Boussidi",
      "Sidi Ali Benyoub",
      "Sidi Brahim",
      "Sidi Chaïb",
      "Sidi Dahou de Zairs",
      "Sidi Hamadouche",
      "Sidi Khaled",
      "Sidi Lahcene",
      "Sidi Yacoub",
      "Tabia",
      "Tafissour",
      "Tefessour",
      "Telagh",
      "Tenira",
      "Tessala",
      "Tilmouni",
      "Zerouala",
    ],
  },
  "23": {
    name: "Annaba",
    domicilePrice: 700,
    stopDeskPrice: 450,
    municipalities: [
      "Annaba",
      "El Bouni",
      "El Hadjar",
      "Sidi Amar",
      "Berrahal",
      "Chetaïbi",
      "Cheurfa",
      "Oued El Aneb",
      "Séraïdi",
      "Treat",
      "Ain Berda",
    ],
  },
  "24": {
    name: "Guelma",
    domicilePrice: 700,
    stopDeskPrice: 450,
    municipalities: [
      "Guelma",
      "Ain Ben Beida",
      "Ain Makhlouf",
      "Ain Regada",
      "Ain Sandel",
      "Belkheir",
      "Ben Djarah",
      "Beni Mezline",
      "Bordj Sabat",
      "Bou Hachana",
      "Bou Hamdane",
      "Bouati Mahmoud",
      "Dahouara",
      "Djeballah Khemissi",
      "El Fedjoudj",
      "Guelaat Bousbaa",
      "Hammam Debagh",
      "Hammam N'Bails",
      "Khezara",
      "Medjez Amar",
      "Medjez Sfa",
      "Nechmaya",
      "Oued Cheham",
      "Oued Fragha",
      "Oued Zenati",
      "Ras El Agba",
      "Roknia",
      "Salaoua Announa",
      "Tamlouka",
    ],
  },
  "25": {
    name: "Constantine",
    domicilePrice: 700,
    stopDeskPrice: 450,
    municipalities: [
      "Constantine",
      "Ain Abid",
      "Ain Smara",
      "Ben Badis",
      "Didouche Mourad",
      "El Khroub",
      "Hamma Bouziane",
      "Ibn Ziad",
      "Messaoud Boudjeriou",
      "Ouled Rahmoune",
      "Zighoud Youcef",
    ],
  },
  "26": {
    name: "Médéa",
    domicilePrice: 750,
    stopDeskPrice: 450,
    municipalities: [
      "Médéa",
      "Ain Boucif",
      "Aziz",
      "Baata",
      "Ben Chicao",
      "Beni Slimane",
      "Berrouaghia",
      "Bir Ben Laabed",
      "Boghar",
      "Bou Aiche",
      "Bouaichoune",
      "Boughzoul",
      "Boughezoul",
      "Chabounia",
      "Chellalet El Adhaoura",
      "Cheniguel",
      "Damiat",
      "Derrag",
      "Diar Echafa",
      "Djuihar",
      "El Azizia",
      "El Guelbelkebir",
      "El Hamdania",
      "El Omaria",
      "El Ouinet",
      "Hannacha",
      "Kef Lakhdar",
      "Khams Djouamaa",
      "Ksar El Boukhari",
      "Meftaha",
      "Meghraoua",
      "Mezerana",
      "Mihoub",
      "Ouamri",
      "Oued Harbil",
      "Ouled Bouachra",
      "Ouled Derradj",
      "Ouled Hellal",
      "Ouled Maaref",
      "Oum El Djalil",
      "Ouzera",
      "Rebaia",
      "Saneg",
      "Sedraya",
      "Seghouane",
      "Si Mahdjoub",
      "Sidi Demed",
      "Sidi Rabie",
      "Sidi Zahar",
      "Sidi Ziane",
      "Souagui",
      "Tablat",
      "Tafraout",
      "Tamesguida",
      "Tlatet Eddouair",
      "Zoubiria",
    ],
  },
  "27": {
    name: "Mostaganem",
    domicilePrice: 800,
    stopDeskPrice: 500,
    municipalities: [
      "Mostaganem",
      "Ain Boudinar",
      "Ain Nouïssy",
      "Ain Sidi Cherif",
      "Ain Tadles",
      "Benabdelmalek Ramdane",
      "Bouguirat",
      "Fornaka",
      "Hadjadj",
      "Hassi Mameche",
      "Kheir Eddine",
      "Khadra",
      "Mansourah",
      "Mazagran",
      "Mesra",
      "Nekmaria",
      "Oued El Kheïr",
      "Ouled Boughalem",
      "Ouled Maallah",
      "Safsaf",
      "Sayada",
      "Sidi Ali",
      "Sidi Bellater",
      "Sidi Lakhdar",
      "Sirat",
      "Souaflia",
      "Sour",
      "Stidia",
      "Tessala",
      "Touahria",
    ],
  },
  "28": {
    name: "M'Sila",
    domicilePrice: 700,
    stopDeskPrice: 450,
    municipalities: [
      "M'Sila",
      "Ain El Hadjel",
      "Ain El Melh",
      "Ain Fares",
      "Ain Rich",
      "Belaïba",
      "Ben Srour",
      "Berhoum",
      "Bou Saâda",
      "Chellal",
      "Dehahna",
      "Djebel Messaad",
      "El Hamel",
      "El Houamed",
      "Khettouti",
      "Khoubana",
      "Maadid",
      "Magra",
      "M'Tarfa",
      "Menaa",
      "Mohamed Boudiaf",
      "Ouanougha",
      "Ouled Addi Guebala",
      "Ouled Derradj",
      "Ouled Madhi",
      "Ouled Mansour",
      "Ouled Sidi Brahim",
      "Oultem",
      "Sidi Aïssa",
      "Sidi Ameur",
      "Sidi Hadjeres",
      "Sidi M'Hamed",
      "Slim",
      "Souamaa",
      "Tamsa",
      "Tarmount",
      "Zarzour",
    ],
  },
  "29": {
    name: "Mascara",
    domicilePrice: 800,
    stopDeskPrice: 500,
    municipalities: [
      "Mascara",
      "Ain Fares",
      "Ain Fekan",
      "Ain Ferah",
      "Ain Frass",
      "Alaimia",
      "Aouf",
      "Beniane",
      "Bou Henni",
      "Chorfa",
      "El Bordj",
      "El Gaada",
      "El Ghomri",
      "El Gueitena",
      "El Keurt",
      "El Menaouer",
      "Ferraguig",
      "Froha",
      "Gharrous",
      "Guerdjoum",
      "Hacine",
      "Khalouia",
      "Makdha",
      "Maoussa",
      "Moulay Slissen",
      "Nesmoth",
      "Oggaz",
      "Oued El Abtal",
      "Oued Taria",
      "Ras El Ain Amirouche",
      "Sedjerara",
      "Sehailia",
      "Sidi Abdeldjebar",
      "Sidi Abdelmoumen",
      "Sidi Boussaid",
      "Sidi Kada",
      "Sig",
      "Tighennif",
      "Tizi",
      "Zahana",
      "Zelamta",
    ],
  },
  "30": {
    name: "Ouargla",
    domicilePrice: 1000,
    stopDeskPrice: 600,
    municipalities: [
      "Ouargla",
      "Ain Beida",
      "Benaceur",
      "Blidet Amor",
      "El Hadjira",
      "El Allia",
      "Hassi Ben Abdellah",
      "Hassi Messaoud",
      "Megarine",
      "N'Goussa",
      "Rouissat",
      "Sidi Khouiled",
      "Sidi Slimane",
      "Taïbet",
      "Tebesbest",
      "Touggourt",
      "Zaouia El Abidia",
    ],
  },
  "31": {
    name: "Oran",
    domicilePrice: 800,
    stopDeskPrice: 450,
    municipalities: [
      "Oran",
      "Ain El Turck",
      "Arzew",
      "Ben Freha",
      "Bethioua",
      "Bir El Djir",
      "Boufatis",
      "El Ançor",
      "El Braya",
      "El Kerma",
      "Es Senia",
      "Gdyel",
      "Hassi Ben Okba",
      "Hassi Bounif",
      "Hassi Mefsoukh",
      "Mers El Kebir",
      "Misserghin",
      "Oued Tlelat",
      "Sidi Chami",
      "Sidi Ben Yebka",
      "Tafraoui",
    ],
  },
  "32": {
    name: "El Bayadh",
    domicilePrice: 1000,
    stopDeskPrice: 600,
    municipalities: [
      "El Bayadh",
      "Boualem",
      "Bougtoub",
      "Boussemghoun",
      "Brezina",
      "Cheguig",
      "Chellala",
      "El Abiodh Sidi Cheikh",
      "El Bnoud",
      "Kef El Ahmar",
      "Labiodh Sidi Cheikh",
      "Rogassa",
      "Sidi Ameur",
      "Sidi Slimane",
      "Sidi Tifour",
      "Stitten",
      "Tousmouline",
    ],
  },
  "34": {
    name: "Bordj Bou Arréridj",
    domicilePrice: 600,
    stopDeskPrice: 400,
    municipalities: [
      "Bordj Bou Arréridj",
      "Ain Taghrout",
      "Ben Daoud",
      "Bir Kasdali",
      "Bordj Ghedir",
      "Bordj Zemmoura",
      "Colla",
      "Djaafra",
      "El Ach",
      "El Achir",
      "El Anseur",
      "El Hamadia",
      "El M'hir",
      "Ghilassa",
      "Haraza",
      "Hasnaoua",
      "Khelil",
      "Ksour",
      "Mansoura",
      "Medjana",
      "Ouled Brahem",
      "Ouled Dahmane",
      "Ouled Sidi Brahim",
      "Rabta",
      "Ras El Oued",
      "Sidi Embarek",
      "Taglait",
      "Teniet En Nasr",
      "Tesmart",
      "Tixter",
    ],
  },
  "35": {
    name: "Boumerdès",
    domicilePrice: 700,
    stopDeskPrice: 450,
    municipalities: [
      "Boumerdès",
      "Afir",
      "Aïn Tagourait",
      "Baghlia",
      "Ben Choud",
      "Beni Amrane",
      "Bordj Menaïel",
      "Boudouaou",
      "Boudouaou El Bahri",
      "Bouzegza Keddara",
      "Chabet El Ameur",
      "Corso",
      "Dellys",
      "Djinet",
      "El Kharrouba",
      "Hammedi",
      "Isser",
      "Khemis El Khechna",
      "Larbatache",
      "Leghata",
      "Naciria",
      "Ouled Aissa",
      "Ouled Hedadj",
      "Ouled Moussa",
      "Si Mustapha",
      "Sidi Daoud",
      "Souk El Had",
      "Taourga",
      "Thenia",
      "Tidjelabine",
      "Timezrit",
      "Zemmouri",
    ],
  },
  "36": {
    name: "El Tarf",
    domicilePrice: 800,
    stopDeskPrice: 500,
    municipalities: [
      "El Tarf",
      "Ain El Assel",
      "Ain Kerma",
      "Asfour",
      "Ben M'Hidi",
      "Berrihane",
      "Besbes",
      "Bougous",
      "Bouhadjar",
      "Bouteldja",
      "Chebaita Mokhtar",
      "Chefia",
      "Echatt",
      "El Kala",
      "El Ouardia",
      "Lahjar",
      "Oued Zitoun",
      "Raml Souk",
      "Souarekh",
      "Zitouna",
    ],
  },
  "39": {
    name: "El Oued",
    domicilePrice: 900,
    stopDeskPrice: 550,
    municipalities: [
      "El Oued",
      "Bayadha",
      "Debila",
      "Djamaa",
      "Douar El Ma",
      "Guemar",
      "Hassi Khalifa",
      "Kouinine",
      "Magrane",
      "Mih Ouensa",
      "M'rara",
      "Nakhla",
      "Oued El Alenda",
      "Oum Touyour",
      "Reguiba",
      "Robbah",
      "Sidi Amrane",
      "Sidi Aoun",
      "Sidi Khellil",
      "Still",
      "Taghzout",
      "Tendla",
      "Trifaoui",
    ],
  },
  "41": {
    name: "Souk Ahras",
    domicilePrice: 750,
    stopDeskPrice: 450,
    municipalities: [
      "Souk Ahras",
      "Ain Soltane",
      "Ain Zana",
      "Bir Bouhouche",
      "Drea",
      "Haddada",
      "Hanencha",
      "Khedara",
      "Khemissa",
      "M'Daourouch",
      "Mechroha",
      "Merahna",
      "Ouled Driss",
      "Ouled Moumen",
      "Ouillen",
      "Ragouba",
      "Safel El Ouiden",
      "Sedrata",
      "Sid Fredj",
      "Taoura",
      "Terraguelt",
      "Tiffech",
      "Zaroura",
    ],
  },
  "42": {
    name: "Tipaza",
    domicilePrice: 750,
    stopDeskPrice: 450,
    municipalities: [
      "Tipaza",
      "Ahmar El Ain",
      "Attatba",
      "Beni Mileuk",
      "Bou Haroun",
      "Bou Ismail",
      "Bourkika",
      "Chaiba",
      "Cherchell",
      "Damous",
      "Douaouda",
      "Fouka",
      "Gouraya",
      "Hadjeret Ennous",
      "Khemisti",
      "Kolea",
      "Larhat",
      "Menaceur",
      "Merad",
      "Messelmoun",
      "Nador",
      "Sidi Amar",
      "Sidi Ghiles",
      "Sidi Rached",
      "Sidi Semiane",
    ],
  },
  "43": {
    name: "Mila",
    domicilePrice: 700,
    stopDeskPrice: 500,
    municipalities: [
      "Mila",
      "Ahmed Rachedi",
      "Ain Beida Harriche",
      "Ain Mellouk",
      "Ain Tine",
      "Benyahia Abderrahmane",
      "Bouhatem",
      "Chelghoum Laid",
      "Chigara",
      "Derrahi Bousselah",
      "El Ayadi Barbes",
      "Ferdjioua",
      "Grarem Gouga",
      "Hamala",
      "Oued Athmania",
      "Oued Endja",
      "Oued Seguen",
      "Rouached",
      "Sidi Khelifa",
      "Sidi Merouane",
      "Tadjenanet",
      "Tassadane Haddada",
      "Teleghma",
      "Terrai Bainen",
      "Tessala Lemtaï",
      "Tiberguent",
      "Yahia Beni Guecha",
      "Zeghaia",
    ],
  },
  "44": {
    name: "Aïn Defla",
    domicilePrice: 750,
    stopDeskPrice: 450,
    municipalities: [
      "Aïn Defla",
      "Aïn Lechiakh",
      "Aïn Soltane",
      "Aïn Torki",
      "Bordj Emir Khaled",
      "Boumedfaa",
      "Djelida",
      "Djendel",
      "El Abadia",
      "El Amra",
      "El Attaf",
      "El Hassania",
      "El Maine",
      "Hammam Righa",
      "Hoceinia",
      "Khemis Miliana",
      "Miliana",
      "Oued Chorfa",
      "Rouina",
      "Sidi Lakhdar",
      "Tacheta Zougagha",
      "Tarik Ibn Ziad",
      "Tiberkanine",
      "Zeddine",
    ],
  },
  "45": {
    name: "Naâma",
    domicilePrice: 1000,
    stopDeskPrice: 600,
    municipalities: [
      "Naâma",
      "Ain Ben Khelil",
      "Ain Safra",
      "Assela",
      "Djeniane Bourzeg",
      "El Biod",
      "Kasdir",
      "Mekmen Ben Amar",
      "Moghrar",
      "Sfissifa",
      "Tiout",
    ],
  },
  "46": {
    name: "Aïn Témouchent",
    domicilePrice: 800,
    stopDeskPrice: 500,
    municipalities: [
      "Aïn Témouchent",
      "Aïn El Arbaa",
      "Aïn Kihal",
      "Aïn Tolba",
      "Beni Saf",
      "Bouzedjar",
      "Chaabet El Ham",
      "Cisneros",
      "El Amria",
      "El Emir Abdelkader",
      "El Malah",
      "El Messaid",
      "Hammam Bou Hadjar",
      "Hassasna",
      "Oued Berkeche",
      "Oued Sabah",
      "Ouled Boudjemaa",
      "Ouled Kihal",
      "Sidi Ben Adda",
      "Sidi Boumedienne",
      "Sidi Ouriache",
      "Sidi Safi",
      "Tamzoura",
      "Terga",
    ],
  },
  "47": {
    name: "Ghardaïa",
    domicilePrice: 1100,
    stopDeskPrice: 700,
    municipalities: [
      "Ghardaïa",
      "Berriane",
      "Bounoura",
      "Dhayet Bendhahoua",
      "El Atteuf",
      "El Guerrara",
      "El Meniaa",
      "Mansoura",
      "Metlili",
      "Sebseb",
      "Zelfana",
    ],
  },
  "48": {
    name: "Relizane",
    domicilePrice: 800,
    stopDeskPrice: 550,
    municipalities: [
      "Relizane",
      "Ain Tarik",
      "Ammi Moussa",
      "Bendaoud",
      "Beni Dergoun",
      "Beni Zentis",
      "Dar Ben Abdellah",
      "Djidioua",
      "El Guettar",
      "El Hamadna",
      "El Matmar",
      "El Ouldja",
      "Had Echkalla",
      "Hamri",
      "Kalaa",
      "Lazharia",
      "Mazouna",
      "Mediouna",
      "Mendes",
      "Oued Essalem",
      "Oued Rhiou",
      "Ouled Aiche",
      "Ouled Sidi Mihoub",
      "Ramka",
      "Sidi Khettab",
      "Sidi Lazereg",
      "Sidi M'Hamed Ben Ali",
      "Sidi Saada",
      "Yellel",
      "Zemalcha",
    ],
  },
  "58": {
    name: "El Meniaa",
    domicilePrice: 1100,
    stopDeskPrice: 700,
    municipalities: ["El Meniaa", "Hassi Gara", "Hassi Fehal", "Megarine"],
  },
};